name: cargo test
on:
  push:
    branches: [ "main" ]
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    name: cargo test / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo test --all-features